sudo: required

language: node_js

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -f Dockerfile -t yusu/react ./

script:
  - docker run -e CI=true yusu/react npm run test -- --coverage

after_success:
  - echo "Test Success"