sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t yusu/react -f Dockerfile.dev .

script:
  - docker run -e CI=true yusu/react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: yusu-react-start
  env: Yusu-react-start-env
  bucket_name: elasticbeanstalk-ap-northeast-2-270304892797
  bucket_path: yusu-react-start
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY